/** @type {import('tailwindcss').Config} */

import defaultTheme from "tailwindcss/defaultTheme";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "bg-apparel1",
    "bg-apparel2",
    "bg-apparel3",
    "bg-apparel4",
    "bg-apparel5",
    "bg-apparel6",
    "bg-electronic1",
    "bg-electronic2",
    "bg-electronic3",
    "bg-electronic4",
    "bg-electronic5",
    "bg-home1",
    "bg-home2",
    "bg-home3",
    "bg-home4",
    "bg-home5",
    "bg-shoe1",
    "bg-shoe2",
    "bg-shoe3",
    "bg-shoe4",
    "bg-shoe5",
    "bg-shoe1_1",
    "bg-shoe1_2",
    "bg-shoe1_3",
  ],
  theme: {
    extend: {
      backgroundImage: {
        apparel1: "url('/src/assets/products/apparel1.jpg')",
        apparel2: "url('/src/assets/products/apparel2.jpg')",
        apparel3: "url('/src/assets/products/apparel3.jpg')",
        apparel4: "url('/src/assets/products/apparel4.jpg')",
        apparel5: "url('/src/assets/products/apparel5.jpg')",
        apparel6: "url('/src/assets/products/apparel6.jpg')",
        electronic1: "url('/src/assets/products/electronic1.jpg')",
        electronic2: "url('/src/assets/products/electronic2.jpg')",
        electronic3: "url('/src/assets/products/electronic3.jpg')",
        electronic4: "url('/src/assets/products/electronic4.jpg')",
        electronic5: "url('/src/assets/products/electronic5.jpg')",
        home1: "url('/src/assets/products/home1.jpg')",
        home2: "url('/src/assets/products/home2.jpg')",
        home3: "url('/src/assets/products/home3.jpg')",
        home4: "url('/src/assets/products/home4.jpg')",
        home5: "url('/src/assets/products/home5.jpg')",
        shoe1: "url('/src/assets/products/shoe1.jpg')",
        shoe2: "url('/src/assets/products/shoe2.jpg')",
        shoe3: "url('/src/assets/products/shoe3.jpg')",
        shoe4: "url('/src/assets/products/shoe4.jpg')",
        shoe5: "url('/src/assets/products/shoe5.jpg')",
        shoe1_1: "url('/src/assets/products/shoe1-1.jpg')",
        shoe1_2: "url('/src/assets/products/shoe1-2.jpg')",
        shoe1_3: "url('/src/assets/products/shoe1-3.jpg')",
      },
      fontFamily: {
        sans: ["Lato", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [],
  mode: "jit",
};
