/** @type {import('tailwindcss').Config} */

import defaultTheme from "tailwindcss/defaultTheme";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "bg-apparel1",
    "bg-apparel2",
    "bg-apparel3",
    "bg-apparel4",
    "bg-apparel5",
    "bg-apparel6",
    "bg-electronic1",
    "bg-electronic2",
    "bg-electronic3",
    "bg-electronic4",
    "bg-electronic5",
    "bg-home1",
    "bg-home2",
    "bg-home3",
    "bg-home4",
    "bg-home5",
    "bg-shoe1",
    "bg-shoe2",
    "bg-shoe3",
    "bg-shoe4",
    "bg-shoe5",
    "bg-shoe1_1",
    "bg-shoe1_2",
    "bg-shoe1_3",
    "bg-banner1",
    "bg-banner2",
    "bg-procat1",
    "bg-procat2",
    "bg-procat3",
  ],
  theme: {
    container: {
      center: true,
      padding: {
        default: "1rem",
        sm: "2rem",
        lg: "4rem",
        xl: "5rem",
        "2xl": "6rem",
      },
    },

    extend: {
      backgroundImage: {
        apparel1: "url('/src/assets/thumbnail/products/apparel1.jpg')",
        apparel2: "url('/src/assets/thumbnail/products/apparel2.jpg')",
        apparel3: "url('/src/assets/thumbnail/products/apparel3.jpg')",
        apparel4: "url('/src/assets/thumbnail/products/apparel4.jpg')",
        apparel5: "url('/src/assets/thumbnail/products/apparel5.jpg')",
        apparel6: "url('/src/assets/thumbnail/products/apparel6.jpg')",
        electronic1: "url('/src/assets/thumbnail/products/electronic1.jpg')",
        electronic2: "url('/src/assets/thumbnail/products/electronic2.jpg')",
        electronic3: "url('/src/assets/thumbnail/products/electronic3.jpg')",
        electronic4: "url('/src/assets/thumbnail/products/electronic4.jpg')",
        electronic5: "url('/src/assets/thumbnail/products/electronic5.jpg')",
        home1: "url('/src/assets/thumbnail/products/home1.jpg')",
        home2: "url('/src/assets/thumbnail/products/home2.jpg')",
        home3: "url('/src/assets/thumbnail/products/home3.jpg')",
        home4: "url('/src/assets/thumbnail/products/home4.jpg')",
        home5: "url('/src/assets/thumbnail/products/home5.jpg')",
        shoe1: "url('/src/assets/thumbnail/products/shoe1.jpg')",
        shoe2: "url('/src/assets/thumbnail/products/shoe2.jpg')",
        shoe3: "url('/src/assets/thumbnail/products/shoe3.jpg')",
        shoe4: "url('/src/assets/thumbnail/products/shoe4.jpg')",
        shoe5: "url('/src/assets/thumbnail/products/shoe5.jpg')",
        shoe1_1: "url('/src/assets/thumbnail/products/shoe1_1.jpg')",
        shoe1_2: "url('/src/assets/thumbnail/products/shoe1_2.jpg')",
        shoe1_3: "url('/src/assets/thumbnail/products/shoe1_3.jpg')",
        banner1: "url(/src/assets/thumbnail/banner/banner1.jpg)",
        banner2: "url(/src/assets/thumbnail/banner/banner2.jpg)",
        procat1: "url(/src/assets/thumbnail/banner/procat1.jpg)",
        procat2: "url(/src/assets/thumbnail/banner/procat2.jpg)",
        procat3: "url(/src/assets/thumbnail/banner/procat3.jpg)",
      },
      fontFamily: {
        sans: ["Lato", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [],
  mode: "jit",
};
