import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  data: [
    {
      productId: 1,
      score: 5,
      comments: 1955,
      title: "Under Armour Men's Tech",
      price: "56.50",
      sold: 2584,
      stock: 727,
      originalPrice: "75.50",
      bgImg: "apparel1",
    },
    {
      productId: 2,
      score: 4,
      comments: 994,
      title: "Women's Lightweight knit Hoodie Sweater Pullover",
      price: "37.5",
      sold: 1257,
      stock: 127,
      originalPrice: "45.5",
      bgImg: "apparel2",
    },
    {
      productId: 3,
      score: 5,
      comments: 1237,
      title: "Black Women's Coat Dress",
      price: "49.95",
      originalPrice: "130.85",
      sold: 5429,
      stock: 311,
      bgImg: "apparel3",
    },
    {
      productId: 4,
      score: 5,
      comments: 10,
      title: "Womens Summer Boho Floral",
      price: "118.9",
      originalPrice: "189.9",
      sold: 2109,
      stock: 179,
      bgImg: "apparel4",
      relatedProduct: [],
    },
    {
      productId: 5,
      score: 5,
      comments: 2251,
      title: "Men Slip On Shoes Casual with Arch Support Insoles",
      price: "80.90",
      sold: 2975,
      stock: 453,
      originalPrice: "75.5",
      bgImg: "shoe1",
    },
    {
      productId: 6,
      score: 5,
      comments: 1237,
      title: "Skecgers Women's Go Joy Walking Shoe Sneaker",
      price: "45.95",
      originalPrice: "64.95",
      sold: 2015,
      stock: 980,
      bgImg: "shoe2",
    },
    {
      productId: 7,
      score: 5,
      comments: 106,
      title: "Walking Shoe Sneaker Womens",
      price: "139.99",
      originalPrice: "189.98",
      sold: 3612,
      stock: 154,
      bgImg: "shoe3",
    },
    {
      productId: 8,
      score: 5,
      comments: 25,
      title: "Women Summer Tosca Shoe",
      price: "104.90",
      originalPrice: "189.90",
      sold: 1224,
      stock: 66,
      bgImg: "shoe4",
    },
    {
      productId: 9,
      title: "Vonanda Velvet Sofa Couch, Mid Century Modern...",
      score: 4,
      comments: 1559,
      price: "469.99",
      originalPrice: "560.99",
      sold: 2151,
      stock: 904,
      bgImage: "home1",
    },
    {
      productId: 10,
      title: "Wireless Headphones Over Ear, Bluetooth Headphones with...",
      score: 5,
      comments: 1411,
      price: "99.98",
      originalPrice: "120.99",
      sold: 1845,
      stock: 370,
      bgImage: "electronic3",
    },
    {
      productId: 11,
      title: "Dimmable Ceiling Light Modern",
      score: 4,
      comments: 545,
      price: "279.99",
      originalPrice: "499.99",
      sold: 995,
      stock: 269,
      bgImage: "home2",
    },
    {
      productId: 12,
      title: "Modern Storage Cabinet with Door & 3 Drawers",
      score: 4.5,
      comments: 336,
      price: "129.99",
      originalPrice: "159.99",
      sold: 756,
      stock: 148,
      bgImage: "home3",
    },
    {
      productId: 13,
      score: 5,
      comments: 2251,
      title: "Men Slip On Shoes Casual with Arch Support Insoles",
      price: "79.90",
      originalPrice: "119.90",
      sold: 589,
      stock: 126,
      bgImg: "shoe1_2",
    },
  ],
};

const productSlice = createSlice({
  name: "product",
  initialState,
  reducers: {},
});

export default productSlice.reducer;
